update commit integrando un pipeline para generar reporte allure, instalando la dependencion rimraf y actualizacion de dependencias

diff --git a/.github/workflows/cypress-ci.yml b/.github/workflows/cypress-ci.yml
--- a/.github/workflows/cypress-ci.yml
+++ b/.github/workflows/cypress-ci.yml
@@ -16,7 +16,7 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
-          node-version: '14.x' # Cambia la versión según necesites
+          node-version: '20.x'  # O la versión que necesites
 
       - name: Install Java 1.8
         uses: actions/setup-java@v3
@@ -34,7 +34,11 @@ jobs:
           npm install -g allure-commandline --save-dev
 
       - name: Run tests and generate report
-        run: npm run test
+        run: |
+          npm run limpiar-reporte
+          npm run ejecutar-pruebas || echo "Cypress tests failed!"
+          npm run generar-reporte
+          npm run abrir-report
 
       - name: Upload Allure results
         uses: actions/upload-artifact@v3
